#!/usr/bin/env bash

SYMBOLS_TO_MANGLE=(
    "CBOR"
    "CBORRepresentable"
    "ObjCCBORDecodingErrorDomain"
    "ObjCCBOREncodingErrorDomain"
    "DSCborBase64DataMarker"
)

# Write to unique file to guard against races during concurrent builds
TMPFILE=$(mktemp)

cat > "$TMPFILE" << EOF

// --------------------------------------------------------------------------------
// WARNING: This header is generated by Scripts/ObjCCBORGenerateManglingHeader.sh.
// Please DO NOT modify its contents manually. Update the script if needed instead.
// --------------------------------------------------------------------------------

#ifndef OBJC_CBOR_MANGLING_H
#define OBJC_CBOR_MANGLING_H

EOF

for symbol in "${SYMBOLS_TO_MANGLE[@]}"
do
  echo "#define $symbol $OBJC_CBOR_MANGLING_PREFIX$symbol" >> "$TMPFILE"
done

cat >> "$TMPFILE" << EOF

#endif /* OBJC_CBOR_MANGLING_H */
EOF

# Atomically move new header to destination
mv "$TMPFILE" "$OBJC_CBOR_MANGLING_HEADER"
