name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Test
      run: xcodebuild
          -project ObjCCBOR.xcodeproj
          -scheme ObjCCBOR
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 11'
          test
